version: 2

project_name: grove

before:
  hooks:
    - go mod tidy

builds:
  - id: grove
    main: ./cmd/grove
    binary: grove
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - id: default
    format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    files:
      - README.md
      - LICENSE*

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - '^chore:'
      - Merge pull request
      - Merge branch

brews:
  - name: grove
    repository:
      owner: henri123lemoine
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    directory: Formula
    homepage: "https://github.com/henri123lemoine/grove"
    description: "Terminal UI for Git worktrees"
    license: "MIT"
    test: |
      system "#{bin}/grove", "--version"
    install: |
      bin.install "grove"

nfpms:
  - id: packages
    package_name: grove
    vendor: henri123lemoine
    homepage: "https://github.com/henri123lemoine/grove"
    description: "Terminal UI for Git worktrees"
    license: MIT
    formats:
      - deb
      - rpm
    bindir: /usr/bin

announce:
  skip: true
